/**
 * Every path into `public/assets`, declared once.
 *
 * Components import from here rather than writing `/assets/...` inline, so a
 * renamed file is a single edit and a missing one is a type error rather than a
 * silent 404 in production. See `public/assets/README.md` for what each slot
 * expects and at what size.
 */

export const ASSETS = {
  logo: {
    /**
     * The supplied artwork, background removed. Both are gold on transparency,
     * which is why there is no light/dark pair: gold holds against the cream
     * page and against the ink panels equally, so one file serves both and
     * there is no second version to keep in sync.
     */
    mark: "/assets/icons/logo-only-removedbg.png",
    /** The wordmark, with "Design · Craft · Elevate" already set beneath it. */
    word: "/assets/icons/nameonly-removedbg.png",
  },
  brand: {
    /**
     * The manufacturing partner's own lockup — mark plus "MODULA" wordmark,
     * supplied as two flat colourways rather than one file recoloured in CSS,
     * because the mark is a solid tile and `invert` would turn it inside out.
     * Brown for the cream page, white for the ink panels and the video.
     */
    modulaBrown: "/assets/icons/modula-logo-brown.png",
    modulaWhite: "/assets/icons/modula-logo-white.png",
    /** Supplied artwork: transparent PNG, navy and red, 4000×1980. */
    jsw: "/assets/logo/india-jsw.png",
    /**
     * The same group mark, cropped tight to the letterforms — for setting
     * inline inside "A JSW Enterprise", where the full file's padding would
     * open a hole in the line.
     */
    jswMark: "/assets/icons/india-jsw-removedbg.png",
    /**
     * The three bars of the Modula mark, exploded out of their tile — the
     * device on its own, with no wordmark. Set large and faint it works as a
     * corner motif; it is decoration, so every call site marks it aria-hidden.
     */
    modulaCorner: "/assets/logo/testimonial-corner.png",
  },
  og: {
    /** Optional override for the card generated by `app/opengraph-image.tsx`. */
    default: "/assets/og/og-default.jpg",
  },
  xteel: {
    /**
     * The exploded-panel render, supplied as a frame sequence rather than one
     * picture: 0095 is the shutter closed, 0100 is it fully apart, and the run
     * back to 0105 closes it again. `XTEEL_FRAMES` below turns that into paths.
     *
     * These are the recoloured copies — the skins repainted white, the
     * composite core left exactly as shot. `scripts/whiten-xteel.js` regenerates
     * them from the untouched originals one directory up.
     */
    frameDir: "/assets/xteel/white",
    firstFrame: 95,
    lastFrame: 105,
  },
} as const;

/**
 * The switch for the supplied artwork.
 *
 * `false` — the mark is the inline SVG drawn in `components/ui/Logo.tsx`, which
 * inherits `currentColor` and therefore works on the cream page and the ink
 * panel with no second file. This is the shipping default, and the site is
 * complete without anything in `public/assets/logo`.
 *
 * `true` — the lockups above are used instead. Flip this only once all four
 * files in `ASSETS.logo` are actually present, or the nav will render a broken
 * image.
 */
export const USE_IMAGE_LOGO = true;

/**
 * Every Xteel frame path, in order. The whole run is rendered into the page and
 * shown one at a time by opacity — swapping a single `src` on scroll re-fetches
 * a frame the first time it is reached, which reads as a flicker mid-scrub.
 */
export const XTEEL_FRAMES = Array.from(
  { length: ASSETS.xteel.lastFrame - ASSETS.xteel.firstFrame + 1 },
  (_, i) =>
    `${ASSETS.xteel.frameDir}/${String(ASSETS.xteel.firstFrame + i).padStart(4, "0")}.webp`
);

/** Intrinsic dimensions of the corner motif, for `next/image`. */
export const MODULA_CORNER_SIZE = { width: 934, height: 888 } as const;

/** Intrinsic dimensions of the two logo files, for `next/image`. */
export const LOGO_MARK_SIZE = { width: 534, height: 467 } as const;
export const LOGO_WORD_SIZE = { width: 886, height: 281 } as const;

/**
 * Intrinsic dimensions of the partner marks.
 *
 * All three files are trimmed to their artwork — no transparent margin — so a
 * height in `em` puts the same amount of *ink* next to the type at every call
 * site, and the two Modula colourways are identical in size so the lockup does
 * not shift when the bar swaps one for the other mid-scroll.
 */
export const MODULA_LOGO_SIZE = { width: 288, height: 80 } as const;
export const JSW_MARK_SIZE = { width: 674, height: 318 } as const;


/**
 * The switch for the supplied Xteel render.
 *
 * `false` — the technology section draws the panel itself, as an exploded
 * cross-section in SVG. Vector, weightless, and correct at any size.
 *
 * `true` — `ASSETS.xteel.exploded` is shown instead: the real product render,
 * which shows the honeycomb core and the true metal the drawing can only
 * suggest. Flip this once the file is committed, not before — a missing file
 * here is a broken image in the middle of the page's main argument.
 */
export const USE_XTEEL_RENDER = true;
