/**
 * Every path into `public/assets`, declared once.
 *
 * Components import from here rather than writing `/assets/...` inline, so a
 * renamed file is a single edit and a missing one is a type error rather than a
 * silent 404 in production. See `public/assets/README.md` for what each slot
 * expects and at what size.
 */

export const ASSETS = {
  logo: {
    /**
     * The supplied artwork, background removed. Both are gold on transparency,
     * which is why there is no light/dark pair: gold holds against the cream
     * page and against the ink panels equally, so one file serves both and
     * there is no second version to keep in sync.
     */
    mark: "/assets/icons/logo-only-removedbg.png",
    /** The wordmark, with "Design · Craft · Elevate" already set beneath it. */
    word: "/assets/icons/nameonly-removedbg.png",
  },
  brand: {
    modula: "/assets/brand/modula.svg",
    /** Supplied artwork: transparent PNG, navy and red, 4000×1980. */
    jsw: "/assets/logo/india-jsw.png",
  },
  og: {
    /** Optional override for the card generated by `app/opengraph-image.tsx`. */
    default: "/assets/og/og-default.jpg",
  },
  xteel: {
    /** The exploded panel render — skin, core, skin — on transparency. */
    exploded: "/assets/xteel/xteel-exploded.png",
  },
} as const;

/**
 * The switch for the supplied artwork.
 *
 * `false` — the mark is the inline SVG drawn in `components/ui/Logo.tsx`, which
 * inherits `currentColor` and therefore works on the cream page and the ink
 * panel with no second file. This is the shipping default, and the site is
 * complete without anything in `public/assets/logo`.
 *
 * `true` — the lockups above are used instead. Flip this only once all four
 * files in `ASSETS.logo` are actually present, or the nav will render a broken
 * image.
 */
export const USE_IMAGE_LOGO = true;

/** Intrinsic dimensions of the two logo files, for `next/image`. */
export const LOGO_MARK_SIZE = { width: 534, height: 467 } as const;
export const LOGO_WORD_SIZE = { width: 886, height: 281 } as const;


/**
 * The switch for the supplied Xteel render.
 *
 * `false` — the technology section draws the panel itself, as an exploded
 * cross-section in SVG. Vector, weightless, and correct at any size.
 *
 * `true` — `ASSETS.xteel.exploded` is shown instead: the real product render,
 * which shows the honeycomb core and the true metal the drawing can only
 * suggest. Flip this once the file is committed, not before — a missing file
 * here is a broken image in the middle of the page's main argument.
 */
export const USE_XTEEL_RENDER = false;
